### ISSUE TITLE
无法在APP端运行

### ISSUE THREAD

**Issue by BTMuli** [dishait/pinia-plugin-unistorage#1]
环境：

+ HbuilderX 3.6.4
+ Vue 3.2.37
+ Pinia 2.0.23
+ Pinia-plugin-unistorage 0.0.8
+ 编译成安卓应用进行调试开发

相关代码：
```js
// store/index.js
import { createPinia } from 'pinia';
import { createUnistorage } from 'pinia-plugin-unistorage';

const store = new createPinia();

store.use(
	createUnistorage({
		serializer: {
			serialize: JSON.stringify,
			deserialize: JSON.parse,
		},
	})
);

export default store;
```

```js
// main.js
import { createSSRApp } from 'vue';
import App from '@/App.vue';
import store from '@/store';

export function createApp() {
	const app = createSSRApp(App);

	app.use(store);

	return {
		app,
		store,
	};
}
```

```js
// store/modules/app.js
import { defineStore } from 'pinia';

const useAppStore = defineStore({
	id: 'app-store',
	state: () => ({
		token: '',
	}),
	getters: {},
	actions: {
		setToken(data) {
			this.token = data;
		}
	unistorage: true
});
export default useAppStore;
```

执行安卓实机调试时终端报错
```sh
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->
 at useStore (app-service.js:5068:15)
 at  (app-service.js:5192:22)
 at  (app-service.js:10250:3)
```
进行 debug 后 console 显示信息：
![image](https://user-images.githubusercontent.com/72692909/200607998-4ce678f1-ae3d-4163-81f5-627543a5f3f4.png)

尝试将 https://www.npmjs.com/package/pinia-plugin-unistorage 的 main.js 覆盖，仍旧报错

**Comment by markthree** [comment]
@BTMuli 你好，请使用 `uniapp` 独有的使用方式，具体可见 👉 [使用](https://github.com/dishait/pinia-plugin-unistorage#%E4%BD%BF%E7%94%A8)

**Comment by BTMuli** [comment]
经过测试发现采用 README 中的引用方式无法解决，该报错是因为在某页面使用 `useStore()` 位于 `data()` 之前导致的，将 `useStore` 放在 `methods` 内即可解决，
![2Y}5WSF AD0HA$LVM6K8IVL](https://user-images.githubusercontent.com/72692909/200753348-34d83df0-0d53-4479-85de-ff90c9fc63c7.png)
但其他小程序端跟H5端采用改写法并未出现问题。

**Comment by markthree** [comment]
@BTMuli 文档有对应描述 👉 [outside-component-usage](https://pinia.web3doc.top/core-concepts/outside-component-usage.html)

**Comment by BTMuli** [comment]
我懂了，这是因为安卓应用没有 SSR 渲染吗？
