### ISSUE TITLE
uniapp项目第一次缓存数据后，刷新页面页面就不展示了，把缓存去掉后刷新，又能正常展示，请问是哪里使用上不对吗？

### ISSUE THREAD

**Issue by LeftProgrammer** [dishait/pinia-plugin-unistorage#11]

**Comment by markthree** [comment]
@LeftProgrammer 靓仔你好，未复现你说的问题，请更新插件到最新版本并提供最小复现仓库

**Comment by markthree** [comment]
@LeftProgrammer 很抱歉靓仔，由于没有提供最小复现，我们并不能够清楚的知道发生了什么问题，所以只能 close 掉了。相关原因可见 → [请提供最小重现](https://antfu.me/posts/why-reproductions-are-required-zh)
