### ISSUE TITLE
不支持ts 写法

### ISSUE THREAD

**Issue by xuxichen** [dishait/pinia-plugin-unistorage#12]
我的pinia 版本是"pinia": "2.0.33","pinia-plugin-unistorage": "^0.0.19", 在ts 项目中
![piniaError](https://github.com/dishait/pinia-plugin-unistorage/assets/18108140/cd699604-cd46-41f6-be6b-b044015ed383)

**Comment by xuxichen** [comment]
解决了

在types 文件夹下创建一个pinia.d.ts 文件
相当于个pinia多申明扩展了一个属性
```
import 'pinia';

declare module 'pinia' {
    export interface DefineStoreOptionsBase<S, Store> {
        unistorage?: boolean | {
            serializer?: {
                serialize: (value: any) => string;
                deserialize: (value: string) => any;
            };
        } | {
            beforeRestore?: (ctx: any) => void;
            afterRestore?: (ctx: any) => void;
        } | {
            key?: string;
            paths?: string[];
        };
    }
}
```
填入如上代码可以支持在
```
defineStore('useStore',{
	unistorage: true, // 是否持久化
}
```
中使用这个unistorage: true, // 是否持久化

**Comment by markthree** [comment]
@xuxichen 未复现，欢迎 pr

**Comment by markthree** [comment]
@xuxichen 也可以下载最新版本的试试，这块已经继承了 [pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate) 的类型

**Comment by xuxichen** [comment]
兄弟，在ts 环境下会有错误提示，

![code_1](https://github.com/user-attachments/assets/3ab35f5f-5ebe-4fc7-844a-0bde4a2b53aa)
当然，ts只是规范你的写法，本身你的是js写法还是可以用的，你应该在 index.d.ts 文件中
![code_2](https://github.com/user-attachments/assets/e9a97cbc-3163-4f61-ba7d-1633bd30669d)
再次导出他们。
还有就是你的README中，
```
npm i pinia-plugin-unistorage -D
```
这个 -D 应该是不对的，这样只是表示开发环境需要用到，这个数据持久化应该是在生产环境也是需要的的。应该要去掉-D

**Comment by markthree** [comment]
@xuxichen 靓仔，关于第一个问题已确认是未导出的缘故。

第二个问题， `-D` 是表示开发环境需要用到哦，但是应用打包时会将 `node_modules` 用到的依赖也打到最终产物当中哦，没问题的。

**Comment by xuxichen** [comment]
确实会打包到最终产物中，但这是不规范的分类，你可以仔细了解一下dependencies、devDependencies 和 peerDependencies的区别

**Comment by markthree** [comment]
> 确实会打包到最终产物中，但这是不规范的分类，你可以仔细了解一下dependencies、devDependencies 和 peerDependencies的区别

很抱歉，靓仔。

这块我认为是 `devDependencies` 哦，只有需要在生产环境下重新 `npm install` 时，我才会考虑不加 `-D`.

**Comment by xuxichen** [comment]
。。。你自己也说是继承[pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate)，你想一想为什么他的项目是没有加 -D，你的项目的功能和他的项目的功能是同一个数据持久化，甚至是扩展。

**Comment by markthree** [comment]
> 。。。你自己也说是继承[pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate)，你想一想为什么他的项目是没有加 -D，你的项目的功能和他的项目的功能是同一个数据持久化，甚至是扩展。

很抱歉，靓仔，这块的规范每个团队不一样哦，另外这块并不影响使用者使
用。

我们团队的应用开发依赖规范是只要不需要在生产环境下重新 `npm install`，就可以加 `-D`，当然这不是一定要这样做的，具体情况还得根据开发需求来。

tip → 使用方式仅供参考，可以按你自己的需求来哦
