### ISSUE TITLE
缺少.d.ts声明文件，可以整合到包里面

### ISSUE THREAD

**Issue by Rain-Hsiang** [dishait/pinia-plugin-unistorage#3]
无法找到模块“pinia-plugin-unistorage”的声明文件。“/Users/rain/Desktop/my-vue3-project/node_modules/.pnpm/pinia-plugin-unistorage@0.0.8/node_modules/pinia-plugin-unistorage/dist/index.js”隐式拥有 "any" 类型。

解决：  
尝试使用 `npm i --save-dev @types/pinia-plugin-unistorage` (如果存在)，
或者添加一个包含 `declare module 'pinia-plugin-unistorage';` 的新声明(.d.ts)文件

**Comment by markthree** [comment]
@Rain-Hsiang 靓仔你好，欢迎 PR

**Comment by Rain-Hsiang** [comment]
> @Rain-Hsiang 靓仔你好，欢迎 PR

小白一个，ts都写不利索，比如uniapp,标签:style属性要放【obj】都不知道怎么写ts,最后还是{...obj}。痛苦，求大佬指导

**Comment by markthree** [comment]
@Rain-Hsiang 靓仔你好，已经支持，可以下载最新的 `npm` 包。

具体更改可见 👉 [chore: add dts](https://github.com/dishait/pinia-plugin-unistorage/commit/3df7803168acf46260e982796e11a01cf3268a94)
