### ISSUE TITLE
开发时，app端重新编译后，数据没有了

### ISSUE THREAD

**Issue by hst-Sunday** [dishait/pinia-plugin-unistorage#7]

**Comment by markthree** [comment]
@hst-Sunday 靓仔你好，未复现你说的问题，可以提供一个最小测试 `demo` 仓库吗？

**Comment by markthree** [comment]
@hst-Sunday 很抱歉靓仔，由于没有提供最小复现，我们并不能够清楚的知道发生了什么问题，所以只能 close 掉了。相关原因可见 → [请提供最小重现](https://antfu.me/posts/why-reproductions-are-required-zh)
