### ISSUE TITLE
uniapp+vue3+ts项目中 'unistorage' does not exist in type 'DefineStoreOptions'.

### ISSUE THREAD

**Issue by smallghh** [dishait/pinia-plugin-unistorage#8]

**Comment by markthree** [comment]
@smallghh 靓仔你好，请提供最小复现仓库

**Comment by markthree** [comment]
@smallghh 很抱歉靓仔，由于没有提供最小复现，我们并不能够清楚的知道发生了什么问题，所以只能 close 掉了。相关原因可见 → [请提供最小重现](https://antfu.me/posts/why-reproductions-are-required-zh)
