### ISSUE TITLE
通过uniapp cli创建的项目, 持久化插件不能实现数据响应式

### ISSUE THREAD

**Issue by lzdml** [dishait/pinia-plugin-unistorage#9]
<img width="799" alt="image" src="https://github.com/dishait/pinia-plugin-unistorage/assets/137750167/4187329d-94eb-45db-b1fd-4db2ed5e755b">
<img width="710" alt="image" src="https://github.com/dishait/pinia-plugin-unistorage/assets/137750167/fe985cbc-80b1-49e0-9f1b-571f640eae03">

**Comment by markthree** [comment]
@lzdml 靓仔你好，请提供最小复现仓库

**Comment by markthree** [comment]
@lzdml 很抱歉靓仔，由于没有提供最小复现，我们并不能够清楚的知道发生了什么问题，所以只能 close 掉了。相关原因可见 → [请提供最小重现](https://antfu.me/posts/why-reproductions-are-required-zh)
